name: "Deploy push from github releases"
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying to ruvds
        uses: appleboy/ssh-action@master # An action made to control Linux servers
        with: # We set all our secrets here for the action, these won't be shown in the action logs
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd  tg/yabeline-scrapper # we move into our app's folder
            git pull # pull latest changes
            /usr/local/go/bin/go test # run tests
            /usr/local/go/bin/go build main.go # we install any missing dependencies
            mv ./main /usr/local/bin/yabeline-scrapper/main # copy app build 
            cp ./.env /usr/local/bin/yabeline-scrapper/.env # copy env file
            systemctl --user restart yabeline-scrapper.service 
